name: ns-flamebringer # define the name of the app

services: # define services
  app: # main Python app
    build: ./ # build using a Dockerfile in the local directory
    restart: always
    secrets:
      - bot-token
      - bot-config
    environment: # pass location of secrets to the container
      FLAMEBRINGER_CONFIG_FILE: /run/secrets/bot-config

secrets:
  bot-token:
    file: ./conf/secrets/token.conf
  bot-config:
    file: ./conf/bot.conf
